### ISSUE TITLE
What to do after installing package/.eslintrc file?

### ISSUE THREAD

**Issue by brylie** [dburles/meteor-eslint#1]
I am confused as to the next step(s) to take after installing this package. Please update the documentation to include a basic example of how this package works.

**Comment by dburles** [comment]
Hey @brylie I really hadn't expected anyone to use it yet considering you'll need to be on a 1.2 release candidate!  I'll definitely expand the docs though. 

But like the brief usage section states, just drop in an `.eslintrc` file into the root of your project (there's a [work in progress one provided](https://gist.github.com/dburles/a2f7ea77189b268b660d)) and you should be up and running. It will lint your code every time you save and dump any warnings to the terminal. You can also run the `meteor lint` command.

**Comment by brylie** [comment]
Ah cool, I didn't realize it would dump to the terminal. Really nice.

As an aside, have you experience with linting Meteor apps using Atom editor?

**Comment by dburles** [comment]
I don't (just Sublime) but you may find this useful http://info.meteor.com/blog/how-to-set-up-atom-and-webstorm-for-meteor-es6-es2015-and-jsx

**Comment by brylie** [comment]
Great link. Thanks for the recommendation and for this useful work!
